//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Monitor.Core.Domain
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IMonitoredEvent 
	{
		Guid Id { get;set; }

		string Title { get;set; }

		DateTime DateTimeUtc { get;set; }

		string Content { get;set; }

		EventCategory EventCategory { get;set; }

	}
}

