//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monitor.SystemTests.Hub {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostMonitoredEvent", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEventRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEvent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor.Core.Domain.EventCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEventResponse))]
    public partial class PostMonitoredEvent : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object requestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object request {
            get {
                return this.requestField;
            }
            set {
                if ((object.ReferenceEquals(this.requestField, value) != true)) {
                    this.requestField = value;
                    this.RaisePropertyChanged("request");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hub.IService")]
    public interface IService {
        
        // CODEGEN: Generating message contract since the operation GetMonitor is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMonitor", ReplyAction="http://tempuri.org/IService/GetMonitorResponse")]
        Monitor.SystemTests.Hub.GetMonitorResponse GetMonitor(Monitor.SystemTests.Hub.GetMonitorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetMonitor", ReplyAction="http://tempuri.org/IService/GetMonitorResponse")]
        System.Threading.Tasks.Task<Monitor.SystemTests.Hub.GetMonitorResponse> GetMonitorAsync(Monitor.SystemTests.Hub.GetMonitorRequest request);
        
        // CODEGEN: Generating message contract since the operation PostMonitoredEvent is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PostMonitoredEvent", ReplyAction="http://tempuri.org/IService/PostMonitoredEventResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEventRequest))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEvent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Monitor.Core.Domain.EventCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Monitor.Core.Domain.MonitoredEventResponse))]
        Monitor.SystemTests.Hub.PostMonitoredEventResponse PostMonitoredEvent(Monitor.SystemTests.Hub.PostMonitoredEventRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PostMonitoredEvent", ReplyAction="http://tempuri.org/IService/PostMonitoredEventResponse")]
        System.Threading.Tasks.Task<Monitor.SystemTests.Hub.PostMonitoredEventResponse> PostMonitoredEventAsync(Monitor.SystemTests.Hub.PostMonitoredEventRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorRequest {
        
        public GetMonitorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMonitorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public System.Nullable<System.Guid> guid;
        
        public GetMonitorResponse() {
        }
        
        public GetMonitorResponse(System.Nullable<System.Guid> guid) {
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMonitoredEventRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Monitor.SystemTests.Hub.PostMonitoredEvent PostMonitoredEvent;
        
        public PostMonitoredEventRequest() {
        }
        
        public PostMonitoredEventRequest(Monitor.SystemTests.Hub.PostMonitoredEvent PostMonitoredEvent) {
            this.PostMonitoredEvent = PostMonitoredEvent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PostMonitoredEventResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/", Order=0)]
        public object anyType;
        
        public PostMonitoredEventResponse() {
        }
        
        public PostMonitoredEventResponse(object anyType) {
            this.anyType = anyType;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Monitor.SystemTests.Hub.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Monitor.SystemTests.Hub.IService>, Monitor.SystemTests.Hub.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor.SystemTests.Hub.GetMonitorResponse Monitor.SystemTests.Hub.IService.GetMonitor(Monitor.SystemTests.Hub.GetMonitorRequest request) {
            return base.Channel.GetMonitor(request);
        }
        
        public System.Nullable<System.Guid> GetMonitor() {
            Monitor.SystemTests.Hub.GetMonitorRequest inValue = new Monitor.SystemTests.Hub.GetMonitorRequest();
            Monitor.SystemTests.Hub.GetMonitorResponse retVal = ((Monitor.SystemTests.Hub.IService)(this)).GetMonitor(inValue);
            return retVal.guid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Monitor.SystemTests.Hub.GetMonitorResponse> Monitor.SystemTests.Hub.IService.GetMonitorAsync(Monitor.SystemTests.Hub.GetMonitorRequest request) {
            return base.Channel.GetMonitorAsync(request);
        }
        
        public System.Threading.Tasks.Task<Monitor.SystemTests.Hub.GetMonitorResponse> GetMonitorAsync() {
            Monitor.SystemTests.Hub.GetMonitorRequest inValue = new Monitor.SystemTests.Hub.GetMonitorRequest();
            return ((Monitor.SystemTests.Hub.IService)(this)).GetMonitorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Monitor.SystemTests.Hub.PostMonitoredEventResponse Monitor.SystemTests.Hub.IService.PostMonitoredEvent(Monitor.SystemTests.Hub.PostMonitoredEventRequest request) {
            return base.Channel.PostMonitoredEvent(request);
        }
        
        public object PostMonitoredEvent(Monitor.SystemTests.Hub.PostMonitoredEvent PostMonitoredEvent1) {
            Monitor.SystemTests.Hub.PostMonitoredEventRequest inValue = new Monitor.SystemTests.Hub.PostMonitoredEventRequest();
            inValue.PostMonitoredEvent = PostMonitoredEvent1;
            Monitor.SystemTests.Hub.PostMonitoredEventResponse retVal = ((Monitor.SystemTests.Hub.IService)(this)).PostMonitoredEvent(inValue);
            return retVal.anyType;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Monitor.SystemTests.Hub.PostMonitoredEventResponse> Monitor.SystemTests.Hub.IService.PostMonitoredEventAsync(Monitor.SystemTests.Hub.PostMonitoredEventRequest request) {
            return base.Channel.PostMonitoredEventAsync(request);
        }
        
        public System.Threading.Tasks.Task<Monitor.SystemTests.Hub.PostMonitoredEventResponse> PostMonitoredEventAsync(Monitor.SystemTests.Hub.PostMonitoredEvent PostMonitoredEvent) {
            Monitor.SystemTests.Hub.PostMonitoredEventRequest inValue = new Monitor.SystemTests.Hub.PostMonitoredEventRequest();
            inValue.PostMonitoredEvent = PostMonitoredEvent;
            return ((Monitor.SystemTests.Hub.IService)(this)).PostMonitoredEventAsync(inValue);
        }
    }
}
